### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by ORCA666** [d4rk007/sak1to-shell#1]
Hello hope you are doing good,
U didn't mentioned any details on compiling the code, hopefully using mingw for [sakito_revshell](https://github.com/d4rk007/sak1to-shell/blob/main/sakito_revshell.c) cz I have some nice ideas for this project :p

**Comment by ORCA666** [comment]
@d4rk007 hellooo, u updated this 7 hrs ago, don't ignore me

**Comment by d4rk007** [comment]
I will add documentation or a build script later if I have time.

**Comment by ORCA666** [comment]
ill be waiting :)

**Comment by d4rk007** [comment]
Compilation documentation added.
